name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Tests - Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure environment with Python ${{ matrix.python-version}}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: bbhx-test
        create-args: >-
          python=${{ matrix.python-version }}
          gcc_linux-64
          gxx_linux-64
          gsl
          lapack
          numpy
          scipy
          Cython
          ipython
          matplotlib
          pytest
          pycbc
        cache-environment: true
        post-cleanup: 'all'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/mikekatz04/BBHx.git@dd4c1f5b5a180ca10e699bd0317238be7480f28b
        pip install .
    - name: Test with pytest
      run: |
        python -m pytest -v tests.py
